### ISSUE TITLE
Floating point values.

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/toml-test#1]
I believe the treatment of 64 bit integers in the test suite is solid, but I think testing floating point values has holes.

It is partially mitigated by the fact that all values are encoded as JSON strings. This means that we can interpret all floating point values as Go does and perform a proper equality test.

However, different languages may have different floating point representations. Which means that some languages might produce different values---which poses problems for an equality test.

In practice, this may not be so much of an issue since floating point conversion is typically well-handled by the language being used. However, it may be worth it to come up with tests for sufficiently small and large numbers that are not reliably represented in practice.

Overall, I'm not sure. And I have only a passing familiarity with the inner workings of floating point representation to know if this is a real issue or not.

**Comment by mmakaay** [comment]
Not an epsilon-related issue, but an issue related to comparing float values.

When comparing "nan" floats, parsing to a float64 and comparing the expected and actual version using `==` will not work (it will always return false). You'll have to check if both values are NaN using `math.IsNaN(floatValue)`. In my codebase, my check to see if I've got a float mismatch looks like this:

``` go
if expectedFloat != actualFloat && !(math.IsNaN(expectedFloat) && math.IsNaN(actualFloat)) {
    // error handling here...
}
```
