### ISSUE TITLE
Inconsistent command-line option parsing

### ISSUE THREAD

**Issue by xlatb** [BurntSushi/toml-test#103]
The usage example shows passing flags to the parser command as extra command-line arguments:

```
Usage: toml-test-v1.0.0-linux-amd64 parser-cmd [ parser-cmd-flags ]
```

And it also contains the following note:

```
Any positional arguments are use as the parser-cmd; to pass flags, remember to
stop toml-test's flag parsing with --

   $ toml-test-v1.0.0-linux-amd64 -- my-parser -x -y
```

Unfortunately this only seems to work consistently for single-character flags. Longer flags seem to be checked for validity against toml-test's own flags.

As an example, the following command is accepted:

```
$ ./toml-test-v1.0.0-linux-amd64 -- /bin/false -x
```

But this one is not:

```
$ ./toml-test-v1.0.0-linux-amd64 -- /bin/false --enable-x
toml-test-v1.0.0-linux-amd64: unknown flag: "--enable-x"
```

Even stranger, the options are allowed through or not depending on whether they match one of toml-test's options. For example, toml-test has an option `--skip`, and thus the following is accepted *as an option to pass to the decoder to be run*:

```
$ ./toml-test-v1.0.0-linux-amd64 -- /bin/false --skip
```

But if we change one letter, it is no longer accepted:

```
$ ./toml-test-v1.0.0-linux-amd64 -- /bin/false --skop
toml-test-v1.0.0-linux-amd64: unknown flag: "--skop"
```

**Comment by arp242** [comment]
I fixed this some time ago in the flag parsing library; I updated it here and seems to work well now.
