### ISSUE TITLE
Back-test TOML versions?

### ISSUE THREAD

**Issue by brandonchinn178** [BurntSushi/toml-test#113]
I'm investigating some TOML libraries in Haskell, and I'm not completely sure what version of TOML they support, but I'm pretty sure they support v0.4.0 or v0.5.0. I'd be open to upgrading them to v1.0.0, but in the meantime, it would be great if I could run `toml-test -version v0.4.0` on them to quickly see how they conform to spec.

Alternatively, if you want to avoid maintaining old versions' tests in perpetuity, you could add releases for old versions of `toml-test` (or add docs somewhere containing github commit hashes) that clearly indicate what version of the spec they adhere to.

**Comment by arp242** [comment]
I went ahead and added a `-toml` flag to select the version (`-version` was already used to show the toml-test version), but still need to expand the list of tests here: https://github.com/BurntSushi/toml-test/blob/master/version.go#L17

**Comment by brandonchinn178** [comment]
That was fast! Thanks, looks like a good start!

**Comment by arp242** [comment]
Yeah, figured it would be useful for the future in any case. For the older versions just need to expand the list of tests; if you get it running against one of those 0.5 or 0.4 Haskell libraries then let me know (or send a PR) to add the appropriate tests in there. Some may have the be split up a bit as they test both newer and older features in the same file.

**Comment by arp242** [comment]
I'll close this because the feature is implemented and I'll use it for future versions (the upcoming TOML 1.1).

Not all the older tests are tagged but I'm not sure how much interest there is to tag all the pre-1.0 tests considering TOML 1.0 is two years old at this point, but if someone wants to work on it then I'll merge it (or help out, if needed).
