### ISSUE TITLE
Bug in Test Case: valid/string/multiline-quotes

### ISSUE THREAD

**Issue by cyanskies** [BurntSushi/toml-test#124]
I get the following message testing my encoder with the precompiled 1.2.0 windows 64bit executable:

    valid/string/multiline-quotes
    BUG IN TEST CASE: could not decode TOML file "valid/string/multiline-quotes.toml":
      toml: line 19 (last key "escaped"): unexpected '""""""'

I'm invoking the test with the following command line: ".\toml-test-v1.2.0.exe .\toml-test-encoder.exe -encoder"

**Comment by arp242** [comment]
1197108 should have fixed that. I got a few things I worked on, I'll release a new version this weekend or next week, time permitting.

**Comment by arp242** [comment]
Released v1.3.0
