### ISSUE TITLE
Add test for tab character

### ISSUE THREAD

**Issue by ndtoan96** [BurntSushi/toml-test#126]
There is an [issue](https://github.com/xoofx/Tomlyn/issues/50) regarding tab character in Tomlyn library.

After reading the [specs](https://toml.io/en/v1.0.0#string) , I found this:

> Any Unicode character may be used except those that must be escaped: backslash and the control characters other than tab, line feed, and carriage return (U+0000 to U+0008, U+000B, U+000C, U+000E to U+001F, U+007F).

> Control characters other than tab are not permitted in a literal string

So I think we should add a valid testcase for tab character in multi-line basic string, single-line literal string and multi-line literal string.

**Comment by arp242** [comment]
https://github.com/BurntSushi/toml-test/blob/master/tests/valid/string/multiline.toml has tab characters, maybe some other too.

It's not clear to me what case exactly is missing for you?

**Comment by arp242** [comment]
But feel free to send a PR with a new test, or more tests.
