### ISSUE TITLE
Add tests for invalid encodings in all string types

### ISSUE THREAD

**Issue by cxw42** [BurntSushi/toml-test#128]
The existing https://github.com/BurntSushi/toml-test/tree/master/tests/invalid/encoding tests basic strings, but not literal, multiline basic, or multiline literal.  As a result, the test suite did not trigger https://github.com/ToruNiina/toml11/issues/199.  Would it be possible to add tests for invalid encodings in the other string types?  Thanks for considering this request!

**Comment by arp242** [comment]
Added the tests and released v1.3.0

**Comment by cxw42** [comment]
Wow!  That was quick! :)  Thanks very much!
