### ISSUE TITLE
Move to toml-lang org?

### ISSUE THREAD

**Issue by parkr** [BurntSushi/toml-test#14]
Hey,

With the creation of the toml-lang org and this test resource as the *de facto* testing resource for parsers, could this repository be moved to that organization? Then this could be upgraded as the TOML spec is bumped. It'd make for better "discovery" and "authority" of this resource.

Thoughts?

**Comment by sammthomson** [comment]
:+1: It might even make sense to put the test fixtures inside the toml-lang/toml repo, to make it easier to collate which test cases are appropriate for which toml version as the spec changes?
