### ISSUE TITLE
Out of Sync with Current Version

### ISSUE THREAD

**Issue by robmuh** [BurntSushi/toml-test#36]
# Um, this doesn't seem accurate any more:

![screen shot 2016-04-20 at 6 19 28 pm](https://cloud.githubusercontent.com/assets/3749067/14692339/748a9b8e-0724-11e6-9842-7fe1c9d73997.png)

Here's the main page:

![screen shot 2016-04-20 at 6 24 22 pm](https://cloud.githubusercontent.com/assets/3749067/14692431/21a2b180-0725-11e6-90df-aff5dbd848f6.png)

I would love to sign up to create some additional tests for the things that are missing. Is there anything specific you would like first?

I see there are different tags corresponding to different TOML versions I suspect. Perhaps a v0.4.0 branch could be added for us to work on together until we get it polished enough to become the main. I have forked and created a v0.4.0 branch and will add the updated tests, if any to it before submitting as a PR.

**Comment by uiri** [comment]
Hi Rob, thanks for opening this issue! I closed this by updating the README in 9ed09bfef
