### ISSUE TITLE
Make toml-test an official TOML product and move to github.com/toml-lang org

### ISSUE THREAD

**Issue by mojombo** [BurntSushi/toml-test#42]
I'd love for toml-test to become the official test suite for TOML implementations. If you're into that idea, we could move it to the toml-lang org on GitHub so people know it's the real deal. Once it's updated for the imminent 1.0 release, I'd like to create an easy way for implementors to get their implementation's test results published on the upcoming TOML marketing website so others can see which implementations are production ready.

**Comment by mojombo** [comment]
@BurntSushi If you're into this idea, I'll put some effort into getting this up to date for the latest TOML on master.

**Comment by BurntSushi** [comment]
@mojombo I'm definitely interested. I haven't had as much time for TOML lately as I'd like, but I'd be happy to hand over or share maintenance of this repo!

**Comment by BurntSushi** [comment]
@mojombo I've invited you!

**Comment by BurntSushi** [comment]
And moving this into the `toml-lang` org sounds good to me!

**Comment by mojombo** [comment]
Awesome! I'll work on getting this compliant with master and then move it into the TOML org. Booyah!

**Comment by samvasko** [comment]
@mojombo I am be happy to help to speed up the transition. I would really like to see some of the pull requests merged.

**Comment by BurntSushi** [comment]
I don't have time, sorry.

**Comment by uiri** [comment]
@pradyunsg @mojombo Are there still plans to move this `toml-test` repo into the toml-lang org?

I have merged in all the non-code change PRs (i.e. more test cases and additions to the README) and cleaned up the easy, "quick fix" issues. Are any of the remaining PRs and issues things which you would like to see merged/fixed before moving the repo?

**Comment by sgarciac** [comment]
It would have been nice if you had created a release for 3.0. I think no post-4.0 features tests should be merged without tagging/releasing a version for 4.0, it will make it easier to follow what features are not yet covered by the suite.

**Comment by eksortso** [comment]
@sgarciac Did you turn all the 0.n's into en-dot-ohs there, or something?

**Comment by arp242** [comment]
Being discussed in the toml repo as well; see my comment there: https://github.com/toml-lang/toml/issues/585#issuecomment-868784840

Not sure if there's any point keeping this one open, so closing it in favour of the issue on the toml repo.
