### ISSUE TITLE
false failure in raw-multiline-string encoder test?

### ISSUE THREAD

**Issue by DBTaylor** [BurntSushi/toml-test#45]
When testing my encoder the raw-multiline-string test fails with:

$ $HOME/go/bin/toml-test -encoder encode.bat raw-multiline-string
Test: raw-multiline-string (valid)

Values for key 'firstnl' differ. Expected value is
This string has a ' quote character. (string), but your encoder produced This string has a ' quote character. (string).

0 passed, 1 failed

The output [output.txt](https://github.com/BurntSushi/toml-test/files/1071348/output.txt) of my encoder looks good to me. It looks like the test suite is maybe expecting the firsnl string to begin with a newline?

**Comment by arp242** [comment]
I'm not sure if I follow what exactly your issue is and what exactly is failing, and there doesn't seem enough information in here to debug the issue. Since this is an old issue I'll just close it, but feel free to follow up with more information and we can reopen and take a look.
