### ISSUE TITLE
Upgrade to TOML 0.5.0

### ISSUE THREAD

**Issue by PMunch** [BurntSushi/toml-test#49]
I used this when developing the TOML parser for Nim, and it was very helpful. But now the spec has updated a while back and this still hasn't been bumped to 0.5.0. Any plans to do it?

**Comment by EpicWink** [comment]
Further from that, what about TOML 1.0-rc1 (and then 1.0 when it comes out? https://github.com/iarna/toml-spec-tests has these tests in already

**Comment by arp242** [comment]
It's now up to date with 0.5, with some parts of 1.0. I'll keep work on getting in to 1.0 i the coming week or so – the differences aren't that huge.
