### ISSUE TITLE
Array of mixed types

### ISSUE THREAD

**Issue by bobfang1992** [BurntSushi/toml-test#63]
Reading the TOML spec, I can see:

> Arrays are square brackets with values inside. Whitespace is ignored. Elements are separated by commas. Arrays can contain values of the same data types as allowed in key/value pairs. Values of different types **may be** mixed.

However, the first test in the `invalid` folder is testing if mixed types is allowed. I am just wondering why that's the case?

**Comment by BurntSushi** [comment]
Because the spec changed... https://github.com/toml-lang/toml/commit/bcd7af2404fc05c0fcf0dab3cf3ebe2fdee7466e
