### ISSUE TITLE
Consistent floating point representation between tests

### ISSUE THREAD

**Issue by yyny** [BurntSushi/toml-test#67]
For example, `tests/valid/exponent-part-float.json` represents floats _without_ a trailing `.0`, but `tests/valid/float-exponent.json` represents floats _with_ a trailing `.0`.

**Comment by filmor** [comment]
@arp242 Could it be that this one got closed accidentally? The formatting is still not completely consistent. Additionally, as I already mentioned in https://github.com/toml-lang/toml/issues/585#issuecomment-644618718, it would be good if the exact representation of the floats in JSON (e.g. number of digits) could be specified.

**Comment by arp242** [comment]
All natural numbers are without a .0, so I figured it was fixed, but I didn't really understand why it mattered either. Anyway, we can talk about that in the PR.
